# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/lcdproc/lcdd.init
# Copyright (C) 2004 - 2026 The T2 SDE Project
# Copyright (C) 1998 - 2003 ROCK Linux Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---
#
# Desc: matrix character lc display server
# Runlevel: 25 rcX
#

main_begin

	block_begin(start, `Starting LCDd')
		check(`D_sbindir/LCDd -c /etc/LCDd.conf &')
	block_end

	block_begin(stop, `Stopping LCDd')
		check(`killall LCDd')
	block_end

main_end
