# --- T2-COPYRIGHT-BEGIN ---
# t2/architecture/x86-64/pkg_glibc32_pre.conf
# Copyright (C) 2016 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

# trailing -gnux32, ...
[ "$SDECFG_X8664_X32" = 1 ] && arch_target="${arch_target%x32}"
