#!/bin/sh
#
# ROCK Linux: /etc/rc.d/init.d/cupsd
#
# Desc: the CUPS print server
# Runlevel: 25 rcX
#

main_begin

    block_begin(start, `Starting cupsd.')
        check(`D_prefix/sbin/cupsd')
    block_end

    block_begin(stop, `Stopping cupsd.')
        check(`killall -15 cupsd')
    block_end

    block_begin(restart, `Restarting cupsd.')
        check(`killall -1 cupsd')
    block_end

main_end

