# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/xen-tools/xend.init
# Copyright (C) 2006 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---
#
# Desc: The XEN backend
# Runlevel: 90 rcX
#

main_begin

    block_begin(start, `Starting xend')
	# some preparations, otherwise xend will fail if not present
	mkdir /var/run/xenstored
	modprobe loop
	check(`xend start')
    block_end

    block_begin(stop, `Stopping xend')
	check(`xend stop')
    block_end

main_end
