# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/vdr/commands.conf
# Copyright (C) 2004 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

== DVB Functions ===== : echo "no function"
-Channel scan Astra    : dvbscan -o vdr -p -x 0 Astra-19.2E > astra-channels.conf
== Restart/Reboot ==== : echo "no function"
-Eject DVD/CD          : mount.sh unmount /mnt/cdfs; mount.sh unmount /mnt/dvd; mount.sh eject /dev/dvd
-Restart VDR           : killall vdr
-Restart System        : shutdown -r now
-Shutdown              : shutdown -h now
===== System ========= : echo "no function"
-View Messages         : tail -n 100 /var/log/messages
-Clear Messages        : echo > /var/log/messages && echo "clean"
-Free Storage          : df -h | awk '{print $5 , "\t" , $6}'
-Sensors               : sensors | awk '{print $1$2}' | egrep -iv "isa|alarm|beep" | sed "s/:/\t: /"
