# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/pyzor/pyzor.init
# Copyright (C) 2004 - 2026 The T2 SDE Project
# Copyright (C) 1998 - 2003 ROCK Linux Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---
#
# Desc: Pyzor Spam Detection Network
# Runlevel: 22 rcX
#

main_begin

    block_begin(start, `Starting pyzord')
	check(`D_bindir/pyzord')
    block_end

    block_begin(stop, `Stopping pyzord')
	check(`killall pyzord')
    block_end

main_end
