# --- T2-COPYRIGHT-BEGIN ---
# t2/architecture/sparc/boot/silo.conf
# Copyright (C) 2004 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

partition=1
read-write
timeout=100
message=/boot/boot.msg
