#!/bin/bash
#
# dRock Linux: /etc/init.d/pdnsd
# Desc: pdnsd - a DNS cache
#
# (C) NOV 2001 by René Rebe <rene.rebe@gmx.net>
#

. /etc/init.d/master.sh

# Functions that are available 
STARTABLE="1"           #start
STOPABLE="1"            #stop

start ()
{
    c_writeln "starting DNS-cache (pdnsd) ..."
    /opt/pdnsd/sbin/pdnsd -d
    return $?
}

stop ()
{
    c_writeln "stopping DNS-cache (pdnsd) ..."
    killall pdnsd
    return $?
}

main $1 $2 $3
