# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/netkit-base/inetd.conf
# Copyright (C) 2004 - 2026 The T2 SDE Project
# Copyright (C) 1998 - 2003 ROCK Linux Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

#
# See "man 8 inetd" for more information.
#
# <service_name> <sock_type> <proto> <flags> <user> <server_path> <args>
#

#
# These are standard services:
#

telnet	stream	tcp	nowait	root	/usr/sbin/tcpd	in.telnetd
ftp	stream	tcp	nowait	root	/usr/sbin/tcpd	in.ftpd

talk	dgram	udp	wait	root	/usr/sbin/tcpd	in.talkd
ntalk	dgram	udp	wait	root	/usr/sbin/tcpd	in.talkd

ident	stream	tcp	wait	nobody	/usr/sbin/tcpd	in.identd -w -e

# rsync	stream	tcp	nowait	root	/usr/sbin/tcpd	/usr/bin/rsync --daemon
# tftp	dgram	udp	wait	nobody	/usr/sbin/tcpd	in.tftpd /tftpboot
# imap	stream	tcp	nowait	root	/usr/sbin/tcpd	/usr/bin/imapd
