#!/bin/sh
#
# ROCK Linux: /etc/rc.d/init.d/openldap
#
# Desc: the OpenLDAP server
# Runlevel: 30 rcX
#

main_begin

   block_begin(start, `Starting OpenLDAP.')
       check(`D_prefix/libexec/slapd -h "ldapi:/// ldap:///" &')
    block_end

   block_begin(stop, `Stopping OpenLDAP.')
       check(`killall -15 D_prefix/libexec/slapd')
   block_end

   block_begin(restart, `Restarting OpenLDAP.')
       check(`killall -1 D_prefix/libexec/slapd')
   block_end

main_end
