# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/portmap/portmap.init
# Copyright (C) 2004 - 2026 The T2 SDE Project
# Copyright (C) 1998 - 2003 ROCK Linux Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---
#
# Desc: The RPC portmapper daemon
# Runlevel: 16 rcX
#

main_begin

    block_begin(start, `Starting RPC portmapper')
	check(`D_sbindir/portmap')
    block_end

    block_begin(stop, `Stopping RPC portmapper')
	check(`killall D_sbindir/portmap')
    block_end

main_end
