#!/bin/sh
#
# ROCK Linux: /etc/rc.d/init.d/ospfd
#
# Desc: OSPF daemon
#
# Runlevel: 25 rcX
#

main_begin

    block_begin(start, `Starting ospfd.')
	check(`D_prefix/sbin/ospfd -d')
    block_end

    block_begin(stop, `Stopping ospfd.')
	check(`killall -15 D_prefix/sbin/ospfd')
    block_end

    block_begin(restart, `Restarting ospfd.')
	check(`killall -1 D_prefix/sbin/ospfd')
    block_end

main_end
