#!/bin/sh
#
# ROCK Linux: /etc/rc.d/init.d/ospf6d
#
# Desc: OSPF daemon for IPv6
#
# Runlevel: 25 rcX
#

main_begin

    block_begin(start, `Starting ospf6d.')
	check(`D_prefix/sbin/ospf6d -d')
    block_end

    block_begin(stop, `Stopping ospf6d.')
	check(`killall -15 D_prefix/sbin/ospf6d')
    block_end

    block_begin(restart, `Restarting ospf6d.')
	check(`killall -1 D_prefix/sbin/ospf6d')
    block_end

main_end
