#!/bin/sh
#
# ROCK Linux: /etc/rc.d/init.d/ripngd
#
# Desc: RIP "next generation" daemon
#
# Runlevel: 25 rcX
#

main_begin

    block_begin(start, `Starting ripngd.')
	check(`D_prefix/sbin/ripngd -d')
    block_end

    block_begin(stop, `Stopping ripngd.')
	check(`killall -15 D_prefix/sbin/ripngd')
    block_end

    block_begin(restart, `Restarting ripngd.')
	check(`killall -1 D_prefix/sbin/ripngd')
    block_end

main_end
