#!/bin/sh
#
# ROCK Linux: /etc/rc.d/init.d/zebra
#
# Desc: zebra routing daemon
#
# Runlevel: 25 rcX
#

main_begin

    block_begin(start, `Starting zebra.')
	check(`D_prefix/sbin/zebra -d')
    block_end

    block_begin(stop, `Stopping zebra.')
	check(`killall -15 D_prefix/sbin/zebra')
    block_end

    block_begin(restart, `Restarting zebra.')
	check(`killall -1 D_prefix/sbin/zebra')
    block_end

main_end
