#!/bin/sh
#
# --- T2-COPYRIGHT-NOTE-BEGIN ---
# This copyright note is auto-generated by ./scripts/Create-CopyPatch.
# 
# T2 SDE: package/.../t2-debug/test_unarchived.sh
# Copyright (C) 2004 - 2005 The T2 SDE Project
# Copyright (C) 1998 - 2003 ROCK Linux Project
# 
# More information can be found in the files COPYING and README.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License. A copy of the
# GNU General Public License can be found in the file COPYING.
# --- T2-COPYRIGHT-NOTE-END ---
#
# List all files which are not listed in /var/adm/flists/*
#
# Output format:
# File-Name
# ...

{
  { find bin boot etc lib sbin usr var opt -type f -printf '~: %p\n'
    cat /var/adm/flists/* ; } | sort +1 |
  awk 'BEGIN { last=""; } $1=="~:" && last!=$2 { print $2; } { last=$2; }'

  ls | egrep -vx 'dev|home|lost\+found|mnt|proc|root|sys|tmp' |
  egrep -vx 'bin|boot|etc|lib|sbin|usr|var|opt'
} |
egrep -xv 'etc/ld.so.cache|usr/share/info/dir|lib/modules/.*/modules.dep'

exit 0
