#!/bin/sh
#
# ROCK Linux: /etc/rc.d/init.d/mysql
#
# Desc: the MySQL server
# Runlevel: 30 rcX
#

main_begin

   block_begin(start, `Starting MySQL Server.')
       check(`D_prefix/opt/mysql/bin/mysqld_safe --datadir=/var/opt/mysql --pid-file=$pid_file &')
   block_end

   block_begin(stop, `Stopping MySQL Server.')
       check(`killall -15 mysqld')
   block_end

   block_begin(restart, `Restarting MySQL Server.')
       check(`killall -1 mysqld')
   block_end

main_end
