#!/bin/sh
#
# ROCK Linux: /etc/rc.d/init.d/mysql
#
# Desc: the MySQL server
# Runlevel: 30 rcX
#

main_begin

   block_begin(start, `Starting MySQL Server.')
       check(`(D_prefix/bin/mysqld_safe >/dev/null 2>&1 &)')
   block_end

   block_begin(stop, `Stopping MySQL Server.')
       check(`killall mysqld')
   block_end

   block_begin(restart, `Restarting MySQL Server.')
       check(`killall -1 mysqld')
   block_end

main_end
