# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/libvirt/libvirtd.init
# Copyright (C) 2012 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---
#
# Desc: Libvirtd Daemon
# Runlevel: 80 rcX
#

main_begin

	block_begin(start, `Starting Libvirtd Daemon')
		check(`D_sbindir/libvirtd --daemon')
	block_end

	block_begin(stop, `Stopping Libvirtd Daemon')
		check(`killall D_sbindir/libvirtd')
	block_end

main_end
