#!/bin/bash
#
# ROCK Linux: /etc/rc.d/init.d/coda-client
#
# Desc: The CODA filesystem client cache manager (venus)
# Runlevel: 35 rcX
#
# (C) FEB 2002 by René Rebe <rene.rebe@gmx.net>
#

main_begin

	block_begin(start, `starting CODA cache manager (venus) ...')
		check(`/opt/coda/sbin/venus &'=
	block_end

	block_begin(stop, `stopping CODA cache manager (venus) ...')
		check(`killall -TERM venus')
		check(`umount /coda')
	block_end

main_end
