# --- T2-COPYRIGHT-NOTE-BEGIN ---
# T2 SDE: misc/archive/hello.nim
# Copyright (C) 2019 - 2022 The T2 SDE Project
# 
# This Copyright note is generated by scripts/Create-CopyPatch,
# more information can be found in the files COPYING and README.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2.
# --- T2-COPYRIGHT-NOTE-END ---

echo "Hello from Nim."
