c Hello World in Fortran (by Clifford)
c
c --- T2-COPYRIGHT-NOTE-BEGIN ---
c This copyright note is auto-generated by ./scripts/Create-CopyPatch.
c 
c T2 SDE: scripts/Config
c Copyright (C) 2004 - 2007 The T2 SDE Project
c Copyright (C) 1998 - 2003 ROCK Linux Project
c
c More information can be found in the files COPYING and README.
c 
c This program is free software; you can redistribute it and/or modify
c it under the terms of the GNU General Public License as published by
c the Free Software Foundation; version 2 of the License. A copy of the
c GNU General Public License can be found in the file COPYING.
c --- T2-COPYRIGHT-NOTE-END ---

	program hello_world
		print *, "Hello World! (A simple Fortran program.)"
	end
