c Hello World in Fortran (by Clifford)
c
c --- ROCK-COPYRIGHT-NOTE-BEGIN ---
c 
c This copyright note is auto-generated by ./scripts/Create-CopyPatch.
c Please add additional copyright information _after_ the line containing
c the ROCK-COPYRIGHT-NOTE-END tag. Otherwise it might get removed by
c the ./scripts/Create-CopyPatch script. Do not edit this copyright text!
c 
c ROCK Linux: rock-src/misc/archive/hello.f
c Copyright (C) 1998 - 2003 ROCK Linux Project
c 
c This program is free software; you can redistribute it and/or modify
c it under the terms of the GNU General Public License as published by
c the Free Software Foundation; either version 2 of the License, or
c (at your option) any later version. A copy of the GNU General Public
c License can be found at Documentation/COPYING.
c 
c Many people helped and are helping developing ROCK Linux. Please
c have a look at http://www.rocklinux.org/ and the Documentation/TEAM
c file for details.
c 
c --- ROCK-COPYRIGHT-NOTE-END ---

	program hello_world
		print *, "Hello World! (A simple Fortran program.)"
	end

