/* 
 * --- T2-COPYRIGHT-NOTE-BEGIN ---
 * T2 SDE: misc/archive/hello.go
 * Copyright (C) 2014 - 2024 The T2 SDE Project
 * 
 * This Copyright note is generated by scripts/Create-CopyPatch,
 * more information can be found in the files COPYING and README.
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2.
 * --- T2-COPYRIGHT-NOTE-END ---
 */

package main
import "fmt"

func main() {
	fmt.Println("Hello from Go.")
}
