/*
 * --- T2-COPYRIGHT-NOTE-BEGIN ---
 * This copyright note is auto-generated by ./scripts/Create-CopyPatch.
 * 
 * T2 SDE: misc/archive/xline.c
 * Copyright (C) 2004 - 2005 The T2 SDE Project
 * Copyright (C) 1998 - 2003 ROCK Linux Project
 * 
 * More information can be found in the files COPYING and README.
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; version 2 of the License. A copy of the
 * GNU General Public License can be found in the file COPYING.
 * --- T2-COPYRIGHT-NOTE-END ---
 */

#include <stdio.h>
#include <time.h>
#include <unistd.h>

int main() {
	char ch,line[512];
	time_t lasttm=0;
	int c=0;
	
	while ( read(0,&ch,1)==1 ) {
		line[c++]=ch;
		if (ch == '\n')
			if (lasttm<time(NULL)-5) {
				line[c-1]=c=0; puts(line); time(&lasttm);
			} else 
				c=0;
		else
			if (c>500) c=500;
	}
	return 0;
}
