#!/usr/bin/expect -f

set qemu [lindex $argv 0]
set kernel [lindex $argv 1]
set initrd [lindex $argv 2]
set append [lindex $argv 3]
set argv [lreplace $argv 0 3]

# Wait enough (forever) until a long-time boot
set timeout 13
#timeout {exit 1}
set send_slow {8 .1}

# Start the guest VM
spawn $qemu -kernel $kernel -initrd $initrd -nographic -append "$append" {*}$argv

expect {
timeout {exit 1}
"T2 SDE early userspace*"
}

expect {
timeout {exit 1}
"*we do not scream, debug shell:"
}

send "echo o > /proc/sysrq-trigger\n"

expect {
timeout {exit 1}
"reboot: Power down"
}
