#!/bin/bash
#
# ROCK Linux /etc/rc.d/init.d/shorewall
#
# Desc: Shorewall Firewall
# Runlevel: 16 rcX
#

main_begin
    block_begin(start, `Starting Shorewall.')
        check(`/sbin/shorewall start')
    block_end
    block_begin(stop, `Stopping Shorewall.')
        check(`/sbin/shorewall stop')
    block_end
    block_begin(restart, `Restarting Shorewall.')
        check(`/sbin/shorewall restart')
    block_end
main_end

