# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/l7-filter/pkg_iptables_pre.conf
# Copyright (C) 2004 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

. $base/package/*/l7-filter/patch_o_matic.in
