# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/dhcp/dhcp.init
# Copyright (C) 2004 - 2026 The T2 SDE Project
# Copyright (C) 1998 - 2003 ROCK Linux Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---
#
# Desc: ISC DHCP Server
# Runlevel: 25 rcX
#

main_begin

    block_begin(start, `Starting dhcpd')
	check(`D_sbindir/dhcpd -q')
    block_end

    block_begin(stop, `Stopping dhcpd')
	check(`killall dhcpd')
    block_end

main_end
