set nocompatible "disable legacy compatibiity
set ruler
syntax on
set colorcolumn=80
set bs=2 "allow backspace over anything including newline
set hlsearch "higligh search
set ignorecase "make search case insensitive
set mouse=""    "disable mouse
set ttymouse="" "disable mouse
"set number
