#!/bin/sh
#
# T2 Linux /etc/rc.d/init.d/ldapdns 
#
# Desc: LDAPDNS Server 
# Runlevel: 55 rcX 
#

main_begin

    block_begin(start, `Starting ldapdns (daemon mode).')
        check(`D_prefix/bin/ldapdns')
    block_end

    block_begin(stop, `Stopping ldapdns (daemon mode).')
        check(`killall -15 D_prefix/bin/ldapdns')
    block_end

    block_begin(stop, `Restarting ldapdns (daemon mode).')
        check(`killall -1 D_prefix/bin/ldapdns')
    block_end

main_end
