# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/avahi/avahi-daemon.init
# Copyright (C) 2006 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

#
# Desc: AVAHI daemon
# Runlevel: 25 rcX
#

main_begin

    block_begin(start, `Starting AVAHI daemon')
	check(`avahi-daemon -D')
    block_end

    block_begin(stop, `Stopping AVAHI daemon')
	check(`avahi-daemon -k')
    block_end

main_end
