# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/avahi/avahi-dnsconfd.init
# Copyright (C) 2006 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

#
# Desc: AVAHI dnsconfd
# Runlevel: 26 rcX
#

main_begin

    block_begin(start, `Starting AVAHI dnsconfd')
	check(`avahi-dnsconfd -D')
    block_end

    block_begin(stop, `Stopping AVAHI dnsconfd')
	check(`avahi-dnsconfd -k')
    block_end

main_end
