# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/smartmontools/smartd.init
# Copyright (C) 2004 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---
#
# ROCK Linux /etc/rc.d/init.d/apache
#
# Desc: The SMART daemon
# Runlevel: 55 rcX
#

main_begin

    block_begin(start, `Starting SMART daemon (smartd)')
	check(`D_sbindir/smartd')
    block_end

    block_begin(stop, `Stopping SMART daemon (smartd)')
	check(`killall D_sbindir/smartd')
    block_end

main_end
