#!/bin/sh
#
#
# Desc: mouse emulation daemon
# Runlevel: 25 rcX
#

[ -f /etc/conf/mouseemu ] && . /etc/conf/mouseemu

main_begin

    block_begin(start, `Starting mouseemu.')
	if [ ! -e /dev/uinput ] ; then
		modprobe uinput
	fi
	if [ -e /dev/uinput ] ; then
		check(`D_prefix/sbin/mouseemu $MOUSEEMU_ARGS')
	else
		false
	fi
    block_end

    block_begin(stop, `Stopping mouseem.')
	check(`killall -15 D_prefix/sbin/mouseemu')
    block_end

main_end

