# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/bacula/bacula-dir.init
# Copyright (C) 2004 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---
#
# Desc: Bacula Director Daemon
# Runlevel: 90 rcX
#

main_begin

    block_begin(start, `Starting Bacula Director Daemon')
	check(`D_sbindir/bacula-dir -v -c D_sysconfdir/bacula-dir.conf')
    block_end
    block_begin(stop, `Stopping Bacula Director Daemon')
	check(`killall bacula-dir')
    block_end

main_end
