# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/bacula/bacula-fd.init
# Copyright (C) 2004 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---
#
# Desc: Bacula File Daemon
# Runlevel: 90 rcX
#

main_begin

    block_begin(start, `Starting Bacula File Daemon')
	check(`D_sbindir/bacula-fd -v -c D_sysconfdir/bacula-fd.conf')
    block_end
    block_begin(stop, `Stopping Bacula File Daemon')
	check(`killall bacula-fd')
    block_end

main_end
