# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/bacula/bacula-sd.init
# Copyright (C) 2004 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---
#
# Desc: Bacula Storage Daemon
# Runlevel: 90 rcX
#

main_begin

    block_begin(start, `Starting Bacula Storage Daemon')
	check(`D_sbindir/bacula-sd -v -c D_sysconfdir/bacula-sd.conf')
    block_end
    block_begin(stop, `Stopping Bacula Storage Daemon')
	check(`killall bacula-sd')
    block_end

main_end
