# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/jboss-as/jboss-as.init
# Copyright (C) 2004 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---
#
# ROCK Linux /etc/rc.d/init.d/jboss
#
# Desc: JBoss J2EE Application Server
# Runlevel: 25 rcX
#

main_begin

    block_begin(start, `Starting jboss')
	check(`D_bindir/run.sh')
    block_end

    block_begin(stop, `Stopping jboss')
	check(`D_bindir/shutdown.sh')
    block_end

main_end
