# --- T2-COPYRIGHT-BEGIN ---
# t2/architecture/avr32/pkg_linux_post.conf
# Copyright (C) 2008 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

# generate a valid kernel config before running autoconf()
if [ "$SDECFG_AVR32_BOARDDEF" != "none" ]; then
	hook_add postpatch 9 "eval $MAKE $makeopt ${SDECFG_AVR32_BOARDDEF}_defconfig ; cp .config .config.defconfig"
else
	hook_add postpatch 9 "eval $MAKE $makeopt defconfig ; cp .config .config.defconfig"
fi

# no acpi support - this generic linux patch breaks avr32 build
var_remove_regex patchfiles ' ' .*acpi-dsdt-initrd.*
