# --- T2-COPYRIGHT-BEGIN ---
# t2/architecture/avr32/pkg_gdb_post.conf
# Copyright (C) 2008 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

var_remove_regex patchfiles ' ' .*uclibc.*patches.*
hook_add postpatch 6 'uclibc_fix_configsub ./config.sub'
