# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/softdog/softdog.init
# Copyright (C) 2004 - 2026 The T2 SDE Project
# Copyright (C) 1998 - 2003 ROCK Linux Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---
#
# Desc: watchdog software
# Runlevel: 19 rcX
#

main_begin

    block_begin(start, `Starting software watchdog timer')
	check(`/sbin/softdog')
    block_end

    block_begin(stop, `Stopping software watchdog timer')
	check(`/sbin/softdog -k')
    block_end

main_end
