# --- T2-COPYRIGHT-BEGIN ---
# t2/architecture/hppa64/pkg_linux_post.conf
# Copyright (C) 2018 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

var_append makeopt ' ' "CROSS32CC=${archprefix}gcc ARCH=parisc64"
var_append makeinstopt ' ' "CROSS32CC=${archprefix}gcc ARCH=parisc64"

arch_sizeof_long=8
arch_sizeof_char_p=8
arch_machine=hppa64
arch_target=${arch_target/hppa/hppa64}
archprefix=${archprefix/hppa/hppa64}

# TODO: wrap kcc "64", too!
var_remove_regex makeopt ' ' 'CC=.*'

# hotfix vdso32 using our user-land compiler, and can not be stripped
GCC_WRAPPER_BYPASS=1
