# --- T2-COPYRIGHT-BEGIN ---
# t2/architecture/hppa64/pkg_linux-firmware_post.conf
# Copyright (C) 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

archprefix=${archprefix/hppa/hppa64}
