# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/rng-tools/rngd.init
# Copyright (C) 2004 - 2026 The T2 SDE Project
# Copyright (C) 1998 - 2004 ROCK Linux Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---
#
# Desc: The i810 hardware random number generator daemon
# Runlevel: 01
#

main_begin

    block_begin(start, `Starting rngd')
	check(`D_sbindir/rngd')
    block_end

    block_begin(stop, `Stopping rngd')
	check(`killall D_sbindir/rngd')
    block_end

main_end
