# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/apcupsd/apcupsd.init
# Copyright (C) 2004 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---
#
# ROCK Linux /etc/rc.d/init.d/apcupsd
#
# Desc: The APC UPS daemon
# Runlevel: 55 rcX
#

main_begin

    block_begin(start, `Starting APC UPS daemon (apcupsd)')
	check(`D_sbindir/apcupsd')
    block_end

    block_begin(stop, `Stopping APC UPS daemon (apcupsd)')
	check(`killall D_sbindir/apcupsd')
    block_end

main_end
