#!/bin/sh
# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/lua/lua-config
# Copyright (C) 2006 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---


version="D_ver"
prefix="/D_prefix"
libdir="D_libdir"
includedir="D_includedir"
pkglibdir="@pkglibdir@"
pkgdatadir="@pkgdatadir@"
LIBS="@LIBS@"
CFLAGS="@CFLAGS@"

usage()
{
  cat <<EOF
Usage: lua-config [OPTIONS]
Options:
 [--prefix]
 [--version]
 [--libdir]
 [--includedir]
 [--libs]
 [--cflags]
 [--pkglibdir]
 [--pkgdatadir]
EOF
  exit $1
}

if test $# -eq 0; then
  usage 1 1>&2
fi

while test $# -gt 0 ; do
  case $1 in
  --version) echo $version ;;
  --prefix) echo $prefix ;;
  --cflags) echo $CFLAGS ;;
  --libdir) echo $libdir ;;
  --includedir) echo $includedir ;;
  --libs) echo $LIBS ;;
  --pkglibdir) echo $pkglibdir ;;
  --pkgdatadir) echo $pkgdatadir ;;
  *)
    usage 1 1>&2
    ;;
  esac
  shift
done
