# --- T2-COPYRIGHT-BEGIN ---
# t2/architecture/blackfin/busybox.conf
# Copyright (C) 2007 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

O CONFIG_SWAPONOFF
O CONFIG_READAHEAD
O CONFIG_HTTPD
O CONFIG_TELNETD
O CONFIG_APP_UDHCPD
O CONFIG_APP_UDHCPC
O CONFIG_ZCIP
