# --- T2-COPYRIGHT-BEGIN ---
# t2/architecture/blackfin/pkg_busybox_post.conf
# Copyright (C) 2007 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

var_append conffiles ' ' $base/architecture/$arch/busybox.conf
