# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/rarian/scrollkeeper-pkg.conf
# Copyright (C) 2004 - 2026 The T2 SDE Project
# Copyright (C) 1998 - 2004 ROCK Linux Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

# exclude some scrollkeeper files - so we do not need to patch every
# single package ...
flistdel="$flistdel|etc/xml/catalog"
if [ $pkg != "scrollkeeper" ]; then
	flistdel="$flistdel|var/.*scrollkeeper_.*cl.xml"
	flistdel="$flistdel|var/.*scrollkeeper/scrollkeeper_docs"
	flistdel="$flistdel|var/.*scrollkeeper/TOC/.*"
	flistdel="$flistdel|var/.*scrollkeeper/index/.*"
fi
