# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/mtools/etc-mtools.conf
# Copyright (C) 2004 - 2026 The T2 SDE Project
# Copyright (C) 1998 - 2003 ROCK Linux Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

drive a:
	file="/dev/floppy/0u1440"
	fat_bits=12
	cylinders=80 heads=2 sectors=18
	mformat_only
