# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/cron/cron.init
# Copyright (C) 2004 - 2026 The T2 SDE Project
# Copyright (C) 1998 - 2003 ROCK Linux Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---
#
# Desc: daemon to execute scheduled commands
# Runlevel: 25 rcX rc2 rc3 rc4 rc5
#

main_begin

    block_begin(start, `Starting cron')
	check(`D_sbindir/cron')
    block_end

    block_begin(stop, `Stopping cron')
	check(`killall D_sbindir/cron')
    block_end

main_end
