# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/zaptel/pkg_module-init-tools_pre.conf
# Copyright (C) 2006 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

# zaptel postmake hook for module-init-tools
zaptel_mit_pm() {
	# modules where we have to run ztcfg after loading
	local zmodules="tor2 wcusb wcfxo wctdm24xxp ztdynamic ztd-eth wct1xxp \
		 wct4xxp wcte11xp pciradio ztd-loc ztdummy torisa"

	cat >> $root/etc/modprobe.conf <<-EOT

	# Zapata Telephony Interface Drivers for Digium cards

	options torisa base=0xd0000
	alias char-major-196 torisa
	alias wcfxs wctdm
	alias wct2xxp wct4xxp
	EOT

	for x in $zmodules; do
		echo "install $x modprobe --ignore-install $x; /sbin/ztcfg"
	done >> $root/etc/modprobe.conf

}
 
hook_add postmake 6 'zaptel_mit_pm'
