# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/partimage/partimage.init
# Copyright (C) 2004 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---
#
# T2 SDE /etc/rc.d/init.d/partimage
#
# Desc: Partimage daemon
# Runlevel: 80 rcX
#

main_begin

    block_begin(start, `Starting Partimage daemon')
	check(`D_sbindir/partimaged -D')
    block_end

    block_begin(stop, `Stopping Partimage daemon')
	check(`killall partimaged')
    block_end

main_end
