#
# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/glibc/nsswitch.conf
# Copyright (C) 2004 - 2026 The T2 SDE Project
# Copyright (C) 1998 - 2003 ROCK Linux Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

#
# Example configuration of GNU Name Service Switch functionality.
#

passwd:		db files
group:		db files
shadow:		db files

hosts:		files dns
networks:	files dns

protocols:	db files
services:	db files
ethers:		db files
rpc:		db files

netgroup:	db files
