# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/nullmailer/nullmailer.init
# Copyright (C) 2004 - 2026 The T2 SDE Project
# Copyright (C) 1998 - 2003 ROCK Linux Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---
#
# Desc: SMTP send-only daemon
# Runlevel: 25 rcX
#

main_begin

    block_begin(start, `Starting nullmailer-send')
	D_sbindir/nullmailer-send &
	sleep 1
	check(`pidof D_sbindir/nullmailer-send > /dev/null')
    block_end

    block_begin(stop, `Stopping nullmailer-send')
	check(`killall nullmailer-send')
    block_end

    block_begin(restart, `Restarting nullmailer-send')
	check(`killall -14 nullmailer-send')
    block_end

main_end
