# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/beep/Makefile.patch
# Copyright (C) 2008 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0 or patched project license
# --- T2-COPYRIGHT-END ---

--- beep-1.2.2/Makefile.vanilla	2008-07-11 22:17:31.000000000 +0200
+++ beep-1.2.2/Makefile	2008-07-11 22:18:06.000000000 +0200
@@ -15,5 +13,5 @@
 
 install : 
 	cp ${EXEC_NAME} ${INSTALL_DIR}
-	rm -f /usr/man/man1/beep.1.bz2
+	rm -f ${MAN_DIR}/beep.1.bz2
 	cp ${MAN_FILE} ${MAN_DIR}
