# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/ps3vuart-tools/ps3hwclock.init
# Copyright (C) 2018 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

# Desc: PS3 hardware clock
# Runlevel: 35 rcX rc2 rc3 rc4 rc5

main_begin

    block_begin(start, `Syncing system time with PS3 hardware clock')
    	check(`date +%s -s @$(ps3dm srtc get_time 1) > /dev/null')
    block_end

    block_begin(stop, `Stopping PS3 hardware clock syncing')
    block_end

main_end
