#!/bin/sh
#
# ROCK Linux: /etc/rc.d/init.d/xinetd
#
# Desc: internet "xinetd(8) super-server"
#
# Runlevel: 25 rcX
#

main_begin

    block_begin(start, `Starting xinetd.')
	check(`D_prefix/sbin/xinetd')
    block_end

    block_begin(stop, `Stopping xinetd.')
	check(`killall -15 D_prefix/sbin/xinetd')
    block_end

    block_begin(restart, `Restarting xinetd.')
	check(`killall -1 D_prefix/sbin/xinetd')
    block_end

main_end
