# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/xfs/xfs.init
# Copyright (C) 2004 - 2026 The T2 SDE Project
# Copyright (C) 1998 - 2004 ROCK Linux Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---
#
# ROCK Linux: /etc/rc.d/init.d/xfs
#
# Desc: X Font Server
# Runlevel: 80 rcX
#

main_begin

    block_begin(start, `Starting xfs')
	check(`/usr/X11/bin/xfs -daemon')
    block_end

    block_begin(stop, `Stopping xfs')
	check(`killall /usr/X11/bin/xfs')
    block_end

main_end
