# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/irda-utils/irda.init
# Copyright (C) 2004 - 2026 The T2 SDE Project
# Copyright (C) 1998 - 2003 ROCK Linux Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---
#
# Desc: infrared wireless communication
# Runlevel: 14 rcX
#

main_begin

    block_begin(start, `Starting irmanager')
	check(`irmanager -d 1')
    block_end

    block_begin(stop, `Shutting down irmanager')
	check(`killall irmanager')
    block_end

main_end
