# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/at/atd.init
# Copyright (C) 2004 - 2026 The T2 SDE Project
# Copyright (C) 1998 - 2003 ROCK Linux Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---
#
# Desc: atd job spooling daemon
# Runlevel: 50 rcX
#

main_begin

    block_begin(start, `Starting atd')
	check(`D_sbindir/atd')
    block_end

    block_begin(stop, `Stopping atd')
	check(`killall D_sbindir/atd')
    block_end

main_end
