# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/openzfs/postlinux.conf
# Copyright (C) 2004 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

# this builds the matching openzfs kernel modules for the building kernel
var_append confopt ' ' --with-config=kernel
var_append makeopt ' ' "CC=$KCC CXX=$CXX LD=$LD AR=$AR OBJCOPY=$OBJCOPY"
var_append confopt ' ' "--with-linux=$moduledir/build --with-linux-obj=$moduledir/build"
var_append confopt ' ' KERNEL_CC=$KCC
atstage cross && var_append confopt ' ' KERNEL_CROSS_COMPILE=$archprefix

# avoid OpenZFS's 'make install' which deletes modules.* metadata
makeinstopt="-C module INSTALL_MOD_PATH=$root modules_install"
