#!/bin/sh

# wait until it's built
if [ -f $root/var/adm/packages/mysql ]; then
	pkgprefix -t mysql
	var_append extraconfopt " " "--with-mysql-lib=$( pkgprefix libdir mysql )/mysql"
	var_append extraconfopt " " "--with-mysql-include=$( pkgprefix includedir mysql )/mysql"
fi
