# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/watchdog/watchdog.init
# Copyright (C) 2024 - 2025 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---
#
# Desc: watchdog daemon
# Runlevel: 20 rcX rc2 rc3 rc5
#

main_begin

    block_begin(start, `Starting watchdog')
	check(`D_sbindir/watchdog')
    block_end

    block_begin(stop, `Stopping watchdog')
	killall D_sbindir/watchdog
    block_end

main_end
