# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/runit/pkg_ntp_post.conf
# Copyright (C) 2004 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

sysconfdir=/etc/ntp

var_append patchfiles ' ' "$base/package/*/runit/patches/ntp-etc_ntp.patch"
