main_begin

    block_begin(start, `Starting prelude-manager (daemon mode).')
        check(`D_prefix/bin/prelude-manager -d')
    block_end

    block_begin(stop, `Stopping prelude-manager (daemon mode).')
        check(`killall -15 D_prefix/bin/prelude-manager')
    block_end

    block_begin(stop, `Restarting prelude-manager (daemon mode).')
        check(`killall -1 D_prefix/bin/prelude-manager')
    block_end

main_end
