# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/grsecurity/pkg_linux-header_pre.conf
# Copyright (C) 2004 - 2026 The T2 SDE Project
# Copyright (C) 1998 - 2003 ROCK Linux Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

. $base/package/*/grsecurity/pkg_linux_pre.conf

# copy include/rsbac to /usr/include/linux too
#hook_add postdoc 1 'cp -rv include/grsecurity $root$includedir/'
