# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/seatd/seatd.init
# Copyright (C) 2021 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---
#
# Desc: seatd daemon
# Runlevel: 98 rcX rc2 rc3 rc5
#

main_begin

	block_begin(start, `Starting seatd')
		D_sbindir/seatd -g video input -l silent &
	block_end

	block_begin(stop, `Stopping seatd')
		check(`killall D_sbindir/seatd')
	block_end

main_end
