#!/bin/sh
#
# ROCK Linux: /etc/rc.d/init.d/dansguardian
#
# Desc: DansGuarian - Filtering pass-through proxy
# Runlevel: 56 rcX
#

main_begin

    block_begin(start, `Starting Dansguardian.')
        check(`D_prefix/sbin/dansguardian')
    block_end

    block_begin(stop, `Stopping Dansguardian.')
        check(`D_prefix/sbin/dansguardian -q')
    block_end

    block_begin(restart, `Restarting Dansguardian.')
        check(`D_prefix/sbin/dansguardian -r')
    block_end

main_end

