# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/polkit/polkit.init
# Copyright (C) 2024 - 2025 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

# Desc: Polkit daemon
# Runlevel: 19
#

main_begin
	block_begin(start, `Starting polkit daemon')
		$D_prefix/lib/polkit-1/polkitd &
	block_end

	block_begin(stop, `Stopping polkit daemon')
		check(`killall polkitd')
	block_end
main_end
