# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/dnsmasq/dnsmasq.init
# Copyright (C) 2006 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

#
# Desc: dnsmasq dns forwading daemon
# Runlevel: 50 rcX
#

main_begin

    block_begin(start, `Starting dnsmasq')
	check(`D_sbindir/dnsmasq')
    block_end

    block_begin(stop, `Stopping dnsmasq')
	check(`killall D_sbindir/dnsmasq')
    block_end

main_end
