# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/ufw/ufw.init
# Copyright (C) 2022 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

#
# Desc UFW Firewall
# Runlevel: 16 rcX
#

main_begin
	block_begin(start, `Starting UFW')
		check(`/lib/ufw/ufw-init start')
	block_end
	block_begin(stop, `Stopping UFW')
		check(`/lib/ufw/ufw-init stop')
	block_end
	block_begin(start, `Restarting UFW')
		check(`/lib/ufw/ufw-init force-reload')
	block_end
main_end
