#
# Configuration file for syslogd(8)
#
# For info about the format of this file, see "man syslog.conf".
#
# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/sysklogd/syslog.conf
# Copyright (C) 2004 - 2026 The T2 SDE Project
# Copyright (C) 1998 - 2003 ROCK Linux Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

#
# save everything (except debug messages) in /var/log/messages
#
*.info				-/var/log/messages

#
# save messages by topic
#
*.warning			/var/log/warn
mail.info			-/var/log/mail

#
# forward emergancy messages to users
#
*.emerg				*
