//
// --- T2-COPYRIGHT-BEGIN ---
// t2/package/*/gn/last_commit_position.h
// Copyright (C) 2023 - 2025 The T2 SDE Project
// SPDX-License-Identifier: GPL-2.0
// --- T2-COPYRIGHT-END ---
//

// Generated by build/gen.py.

#ifndef OUT_LAST_COMMIT_POSITION_H_
#define OUT_LAST_COMMIT_POSITION_H_

#define LAST_COMMIT_POSITION_NUM 2222
#define LAST_COMMIT_POSITION "2222 (18602f6cf116)"

#endif  // OUT_LAST_COMMIT_POSITION_H_
