# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/vdr-mplayer/mp3sources.conf
# Copyright (C) 2004 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

/mnt/dvd;DVD-Audio;1
/mnt/cdfs;CD-Audio;1
/mvideo/music;Network-Storage;1

#Or if you want only WAV files to be displayed:
#/var/mnt/cdfs;CD-Audio;1;*.wav
