#!/bin/sh
# 
#
# Desc: MPD (Music Player Daemon)
# Runlevel: 90 rcX
#

main_begin

    block_begin(start, `Starting Music Player Daemon (MPD).')
        check(`D_bindir/mpd')
    block_end

    block_begin(stop, `Stopping Music Player Daemon (MPD).')
        check(`killall -15 D_bindir/mpd')
    block_end

    block_begin(update-db, `Updating Music Player Daemon (MPD) database.')
        check(`D_bindir/mpd --update-db')
    block_end

main_end
