#!/bin/sh -x
if [ "$ROCKCFG_PKG_UCLIBC_USEIT" == "1" ]; then
	pkg_uclibc_dir=$base/package/base/uclibc

	if [ $pkg != "gettext" ]; then
		var_append flistdel "|" "usr/share/locale/locale.alias"
	fi

	# the most tipical fix is to config.sub
	#
	uclibc_fix_configsub() {
	local x; for x; do
		echo "uclibc_fix_configsub: adding uclibc_arch_target support to $x"
        	cp -f $x $x.orig
		sed -e 's,\([-]\?linux\)-gnu\*,\1-gnu\* | \1-uclibc\*,g' $x.orig > $x
		diff -u $x.orig $x || true
	done
	}
	uclibc_auto_fix_configsub() {
		local f
		for f in . ./config ./support; do
			if [ -e $f/config.sub ] ; then
				if ! grep -q '\-uclibc' $f/config.sub; then
				uclibc_fix_configsub $f/config.sub
				fi
			fi
		done
	}
	uclibc_findall_fix_configsub() {
		local f
		for f in `find . -name config.sub`; do
			uclibc_fix_configsub $f
		done
	}


	# FIXME: what makes uclibc_fix_addcases different than uclibc_fix_configsub? //mnemoc
	uclibc_fix_addcases() {
		local file; for file; do
			echo "uclibc_fix_addcases: adding *-linux-uclibc* support to $file"
			cp -f $file $file.orig
			sed -i -e 's,\([^ ]*\)linux-gnu\*\(.*\)\([\)\\]\),\1linux-gnu* | \1linux-uclibc*\2\3,g' $file
			diff -u $file.orig $file || true
		done
	}

	uclibc_fix_addcases2() {
		local file; for file; do
			echo "uclibc_fix_addcases2: adding *-linux-uclibc* support to $file"
			cp -f $file $file.orig
			sed -i -e 's,\(  *.*\)linux-gnu\*)\(.*\)\;\;$,\1linux-uclibc*)\2;;\n\1linux-gnu*)\2;;,g' \
			       -e 's,\(  *.*\)linux-gnu\*)\(.*[^;][^;]\)$,\1linux-uclibc* \| \\\n\1linux-gnu*)\2,g' \
				$file
			diff -u $file.orig $file || true
		done
	}
	# fix tipical locations
	hook_add postpatch 5 'uclibc_auto_fix_configsub'

	# and some others
	case "$pkg" in
		gcc)
		hook_add postpatch 6 'uclibc_fix_configsub boehm-gc/config.sub'
		;;
		apache|minicom|nmap|expat)
		hook_add postpatch 6 'uclibc_findall_fix_configsub'
		;;
		ntp)
		hook_add postpatch 6 'uclibc_fix_configsub sntp/config.sub'
		;;
		lzo)
		hook_add postpatch 6 'uclibc_fix_configsub acconfig/config.sub'
		;;
		binutils)
		hook_add postpatch 4 'uclibc_fix_addcases ./bfd/config.bfd ./bfd/configure \
			./bfd/configure.in ./ld/configure.tgt'
		hook_add postpatch 5 'uclibc_fix_addcases2 ./gas/configure ./gas/configure.in'
		;;
		gdb)
		hook_add postpatch 4 'uclibc_fix_addcases ./bfd/config.bfd ./bfd/configure'
		;;
		bdb)
		hook_add postpatch 6 'uclibc_fix_configsub ./dist/config.sub'
		;;
		bdb33)
		hook_add postpatch 6 'uclibc_fix_configsub ./dist/config.sub'
		hook_add postpatch 6 'uclibc_fix_configsub ./dist/configure'
		;;
		a2ps)
		hook_add postpatch 6 'uclibc_fix_configsub ./auxdir/config.sub'
		;;
		pidentd)
		hook_add postpatch 6 'uclibc_fix_configsub ./aux/config.sub'
		;;
		apollon)
		hook_add postpatch 6 'uclibc_fix_configsub ./admin/config.sub'
		;;
		openldap)
		hook_add postpatch 6 'uclibc_fix_configsub ./contrib/ldapc++/config.sub'
		hook_add postpatch 6 'uclibc_fix_configsub ./build/config.sub'
		;;
		pkgconfig)
		hook_add postpatch 6 'uclibc_fix_configsub ./configure'
		hook_add postpatch 6 'uclibc_fix_configsub ./glib-1.2.8/ltconfig'
		hook_add postpatch 6 'uclibc_fix_configsub ./glib-1.2.8/config.sub'
		;;
		libsigc++12)
		hook_add postpatch 6 'uclibc_fix_configsub ./scripts/config.sub'
		;;
		libsigc++1)
		hook_add postpatch 6 'uclibc_fix_configsub ./scripts/config.sub'
		hook_add postpatch 6 'uclibc_fix_configsub ./scripts/ltconfig'
		;;
		jasper)
		hook_add preconf 6 'uclibc_fix_configsub ./acaux/config.sub'
		hook_add preconf 6 'uclibc_fix_configsub ./configure'
		hook_add preconf 6 'uclibc_fix_configsub ./aclocal.m4'
		;;
		gdbm)
		hook_add postpatch 6 'uclibc_fix_configsub ./configure'
		;;
		mono)
		hook_add postpatch 6 'uclibc_fix_configsub ./libgc/config.sub'
		hook_add postpatch 6 'uclibc_fix_configsub ./libgc/configure'
		hook_add postpatch 6 'uclibc_fix_configsub ./libgc/libtool.m4'
		;;
		gsmlib)
		hook_add postpatch 6 'uclibc_fix_configsub ./configure'
		hook_add postpatch 6 'uclibc_fix_configsub ./aclocal.m4'
		hook_add postpatch 6 'uclibc_fix_configsub ./scripts/config.sub'
		hook_add postpatch 6 'uclibc_fix_configsub ./scripts/ltconfig'
		;;
		libxml1|librep)
		hook_add postpatch 6 'uclibc_fix_configsub ./configure'
		hook_add postpatch 6 'uclibc_fix_configsub ./aclocal.m4'
		;;
		fribidi)
		hook_add postpatch 6 'uclibc_fix_configsub ./configure'
		;;
		rpm)
		hook_add postpatch 6 'uclibc_fix_configsub ./*/config.sub'
		hook_add postpatch 6 'uclibc_fix_configsub ./*/configure'
		hook_add postpatch 6 'uclibc_fix_configsub ./*/aclocal.m4'
		hook_add postpatch 6 'uclibc_fix_configsub ./*/*/config.sub'
		hook_add postpatch 6 'uclibc_fix_configsub ./*/*/configure'
		;;
		libgd)
		hook_add postpatch 6 'uclibc_fix_configsub ./configure'
		hook_add postpatch 6 'uclibc_fix_configsub ./aclocal.m4'
		hook_add postpatch 6 'uclibc_fix_configsub ./config/config.sub'
		;;
	esac

	# same package translations to look for patches
	case "$pkg" in
		linux24*)
			pkg_uclibc_patchdir=$pkg_uclibc_dir/patches/linux24 ;;
		linux26*|linux-header)
			pkg_uclibc_patchdir=$pkg_uclibc_dir/patches/linux26 ;;
		*)
			pkg_uclibc_patchdir=$pkg_uclibc_dir/patches/$pkg ;;
	esac

	# patching
	if [ "`echo $pkg_uclibc_patchdir-*.patch`" != "$pkg_uclibc_patchdir-*.patch" ]; then
		echo_status "uClibc: appending patches..."
		var_append patchfiles ' ' "`echo $pkg_uclibc_patchdir-*.patch`"
	fi
	[ -f $pkg_uclibc_patchdir.conf ] && . $pkg_uclibc_patchdir.conf
fi
