# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/uclibc/pkg_ltrace_post.conf
# Copyright (C) 2004 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

hook_add premake 5 'ln -s linux-gnu sysdeps/linux-uclibc'
