# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/uclibc/pkg_e2fsprogs_post.conf
# Copyright (C) 2008 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

hook_add preconf 9 "var_append confopt ' ' '--disable-tls'"
