# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/uclibc/pkg_kbd_post.conf
# Copyright (C) 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

var_append GCC_WRAPPER_APPEND ' ' -c?:-lintl
