# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/uclibc/pkg_gawk_post.conf
# Copyright (C) 2016 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

[ "$SDECFG_STATIC" != 1 ] ||
	hook_add premake 5 'sed -i -e "s,#define \(DYNAMIC\) .*,#undef \1," config.h'
