# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/uclibc/pkg_perl_post.conf
# Copyright (C) 2006 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

perl_uclibc_hotfix() {
	# eaccess missing on uClibc
	echo "Changing eaccess -> undef"
	sed -e "s/d_eaccess='define'/d_eaccess='undef'/g" -i config.sh
}

if ! atstage native; then
	hook_add premake 1 perl_uclibc_hotfix
fi
