# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/uclibc/pkg_cpufrequtils_post.conf
# Copyright (C) 2006 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

export LIBS="-lintl"
