# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/uclibc/pkg_psmisc_post.conf
# Copyright (C) 2007 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

atstage cross && pkginstalled gettext && test "$SDECFG_DISABLE_NLS" = "0" && export LIBS="-lintl"
