# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/uclibc/pkg_irssi_post.conf
# Copyright (C) 2004 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

export LD_LIBRARY_PATH="/lib:/usr/lib:"
for x in /opt/*/lib; do
	[ -d $x ] && export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$x"; done
