# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/uclibc/pkg_usbutils_post.conf
# Copyright (C) 2007 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

hook_add preconf 1 'echo "ac_cv_func_malloc_0_nonnull=yes" >> config.cache'
