# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/uclibc/pkg_gdb_post.conf
# Copyright (C) 2004 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

if [ -f /usr/lib/libintl.a ]; then
	export LDFLAGS="$LDFLAGS /usr/lib/libintl.a"
fi

hook_add postpatch 5 'echo bash_cv_have_mbstate_t=yes >> readline/config.cache'
