# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/uclibc/pkg_zfs-fuse_post.conf
# Copyright (C) 2007 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

var_append sconsopt ' ' 'debug=0' # assert code does not build with uClibc ...
