#!/bin/sh
#
# T2: /etc/rc.d/init.d/krb5-admin
#
# Desc: the Kerberos 5 Admin server
# Runlevel: 30 rcX
#

main_begin

   block_begin(start, `Starting Kerberos Admin.')
       check(`D_sbindir/kadmind &')
   block_end

   block_begin(stop, `Stopping Kerberos Admin.')
       check(`killall -15 kadmind')

   block_begin(restart, `Restarting Kerberos Admin.')
       check(`killall -1 kadmind')
   block_end

main_end
