#!/bin/sh
#
# T2: /etc/rc.d/init.d/krb5-kdc
#
# Desc: the Kerberos 5 Domain Controller server
# Runlevel: 30 rcX
#

main_begin

   block_begin(start, `Starting Kerberos Domain Controller.')
       check(`D_sbindir/kdc --detach')
   block_end

   block_begin(stop, `Stopping Kerberos Domain Controller.')
       check(`killall -15 kdc')
   block_end

   block_begin(restart, `Restarting Kerberos Domain Controller.')
       check(`killall -1 kdc')
   block_end

main_end
