#!/bin/sh
if pkginstalled heimdal && [ $stagelevel -ge 5 ]; then
	[ -x krb5-config ] && KRB5PREFIX="=`krb5-config --prefix`"

	#Catch alls for kerberos configs
	var_append extraconfopt " " "--with-kerberos"	#This usually supports 4 only
	#var_append extraconfopt " " "--with-krb4"	#4 Only and not recommended
	var_append extraconfopt " " "--with-krb5"
	var_append extraconfopt " " "--with-kerberos5"	#From openssh
	var_append extraconfopt " " "--with-gss"	#From mutt
	var_append extraconfopt " " "--with-gssapi$KRB5PREFIX"		#From cvs
	var_append extraconfopt " " "--enable-gssapi$KRB5PREFIX"	#From cyrus-sasl2

	if [ "$KRB5PREFIX" ]; then
		var_append extraconfopt " " "--with-gssapi-includes$KRB5PREFIX/include"	# From curl
		var_append extraconfopt " " "--with-gssapi-libs$KRB5PREFIX/lib"		# From curl
	fi
fi
