#!/bin/sh

if pkginstalled heimdal ; then
	#Catch alls for kerberos configs
	var_append extraconfopt " " "--with-kerberos"	#This usually supports 4 only
	#var_append extraconfopt " " "--with-krb4"	#4 Only and not recommended
	var_append extraconfopt " " "--with-krb5"
	var_append extraconfopt " " "--with-kerberos5"	#From openssh
	var_append extraconfopt " " "--with-gssapi=/opt/heimdal"	#From cvs
	var_append extraconfopt " " "--with-gss"	#From mutt

fi
