#!/bin/sh

# We have to set JAVA_HOME environment variable. For this we
# check every jdk we know and verify if it is installed.

JAVA_EVERYJDK="sun-jdk-150 sun-jdk-142 ibm-jdk-142 blackdown-jdk"

[ "$desc_F" != "${desc_F/KAFFE}" ] &&
	JAVA_EVERYJDK="kaffe $JAVA_EVERYJDK"

for jdk in $JAVA_EVERYJDK; do
	if pkginstalled $jdk; then
		# Make java home available to java packages.
		export JAVA_HOME=$root/$(pkgprefix $jdk)

		# Determine the java version.
		# Todo: might be important to some packages.

		break
	fi
done
unset jdk JAVA_EVERYJDK

if pkginstalled java-dirtree; then
	CLASSPATH="/$( pkgprefix libdir java-dirtree):$CLASSPATH"
	export CLASSPATH
fi

