#!/bin/sh
# --- T2-COPYRIGHT-BEGIN ---
# t2/scripts/Apply
# Copyright (C) 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---


tmp=$(mktemp)

curl "$1" > $tmp

for p in p0 p1; do
	patch --dry-run -$p < $tmp > /dev/null || continue
	patch -$p < $tmp && break
done

toadd=$(sed -n '/.* \(.*\)[[:space:]](nonexistent)/s//\1/p' < $tmp)
[ "$toadd" ] && svn add --parents $toadd

rm -f $tmp
