#!/usr/bin/env bash
# --- T2-COPYRIGHT-BEGIN ---
# t2/scripts/Bootstrap
# Copyright (C) 2022 - 2025 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

set -e

pkgs="bash zstd sed gawk"
case $(uname -o) in
QNX) pkgs="$pkgs ncurses" ;;
esac

mkdir -p src

SDECFG_PARALLEL="$(getconf NPROCESSORS_ONLN)"

for p in $pkgs; do
	url=$(sed -n '/\[D\] /{ s,\[D\] [^ ]* \([^ ]*\) \([^ ]*\),\2\1,; p; q;}' package/*/$p/$p.desc)
	file=${url##*/}

	[ ! -e src/$file ] && curl -L -C - -o src/$file.tmp "$url" && mv src/$file{.tmp,}
	(
		cd src
		tar xf $file
		cd ${file%.tar*}
		[ -e configure -a ! -e Makefile ] && ./configure
		make -j${SDECFG_PARALLEL:-1}
		make install
	)
done

mkdir -p /var/adm/flists /etc/profile.d

echo "Essential bootstrap done. To finalize a minimal t2/homebrew, simply first run:"
echo "	./t2 inst -deps=none xz coreutils findutils tar pkgconfig"
echo ""
echo "To use Subversion, also install:"
echo "	./t2 inst -deps=none apr apr-util openssl utf8proc python scons serf sqlite subversion"
