#!/usr/bin/env bash
#
# --- T2-COPYRIGHT-BEGIN ---
# t2/scripts/Create-SrcTar
# Copyright (C) 2004 - 2026 The T2 SDE Project
# Copyright (C) 1998 - 2003 ROCK Linux Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

eval "`grep -A 10 '\[BEGIN\]' scripts/parse-config | grep -B 10 '\[END\]'`"

echo -n 'Creating source tar ... '

# Create temp source base dir
#
src="`mktemp -d -p $PWD src.srctar.XXXXXXXXXX`"
rm -rf $src/t2-src-$sdever
mkdir -p $src/t2-src-$sdever
#
for x in scripts target misc package architecture doc
do
	ln -s ../../$x $src/t2-src-$sdever/$x
done

# Create tar file
#
cd $src
tar --use-compress-program=bzip2 --owner root --group root \
    --exclude .svn --exclude CVS -cf ${1:-t2-src-$sdever.tar.bz2} t2-src-$sdever/*/*

# Done.
#
cd $base
rm -rf $src/
du -sh ${1:-t2-src-$sdever.tar.bz2} | tr '\t' ' '
