#!/bin/bash

tempfile=`mktemp`

counter=100
for pkg in $( ./scripts/Create-PkgList | cut -f4,5 -d' ' | tr ' ' / )
do
	xcounter=$counter
	[ $pkg = base/rock-debug ] && xcounter=999
	[ $pkg = base/rock-src ] && xcounter=998
	sed -e 's,^\(\[P\] .* \)[0-9\.][0-9\.]*$,\1'$xcounter'.000,' \
		< package/$pkg/${pkg#*/}.desc > $tempfile
	diff -u ./package/$pkg/${pkg#*/}.desc $tempfile
	[ $xcounter = $counter ] && counter=$(( $counter + 1 ))
done

