#!/bin/bash

tempfile=`mktemp`

counter=1000
for pkg in $( ./scripts/Create-PkgList | cut -f4,5 -d' ' | tr ' ' / )
do
	xcounter="${counter%?}.${counter#???}00"
	[ $pkg = base/rock-debug ] && xcounter=999.900
	[ $pkg = base/rock-src ] && xcounter=999.800
	sed -e 's,^\(\[P\] .* \)[0-9\.][0-9\.]*$,\1'$xcounter',' \
		< package/$pkg/${pkg#*/}.desc > $tempfile
	diff -u ./package/$pkg/${pkg#*/}.desc $tempfile
	(( counter = counter + 1 ))
done

