dnl --- T2-COPYRIGHT-BEGIN ---
dnl t2/architecture/arm64/linux-apple.m4
dnl Copyright (C) 2025 The T2 SDE Project
dnl SPDX-License-Identifier: GPL-2.0
dnl --- T2-COPYRIGHT-END ---

CONFIG_PCIE_APPLE=m
CONFIG_APPLE_DART=y
CONFIG_APPLE_RTKIT=y
CONFIG_APPLE_SART=y
CONFIG_APPLE_MAILBOX=y
CONFIG_APPLE_PMGR_PWRSTATE=y
CONFIG_PINCTRL_APPLE_GPIO=y
CONFIG_I2C_APPLE=y
CONFIG_BLK_DEV_NVME_APPLE=m
CONFIG_USB_DWC3_DUAL_ROLE=y
