# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/bind/bind.init
# Copyright (C) 2004 - 2026 The T2 SDE Project
# Copyright (C) 1998 - 2003 ROCK Linux Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---
#
# Desc: ISC DNS Server
# Runlevel: 25 rcX
#

main_begin

    block_begin(start, `Starting named')
	check(`D_sbindir/named')
    block_end

    block_begin(stop, `Stopping named')
	check(`killall named')
    block_end

main_end
