# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/kea/kea-dhcp-ddns.init
# Copyright (C) 2021 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---
#
# Desc: kea-dhcp-ddns daemon
# Runlevel: 98 rcX
#

main_begin

	block_begin(start, `Starting kea-dhcp-ddns')
		D_sbindir/kea-dhcp-ddns -c /etc/kea/kea-dhcp-ddns.conf &> /var/log/kea-dhcp-ddns.log &
	block_end

	block_begin(stop, `Stopping kea-dhcp-ddns')
		check(`killall D_sbindir/kea-dhcp-ddns')
	block_end

main_end
