# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/kea/kea-ctrl-agent.init
# Copyright (C) 2021 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---
#
# Desc: kea-ctrl-agent daemon
# Runlevel: 98 rcX
#

main_begin

	block_begin(start, `Starting kea-ctrl-agent')
		D_sbindir/kea-ctrl-agent -c /etc/kea/kea-ctrl-agent.conf &> /var/log/kea-ctrl-agent.log &
	block_end

	block_begin(stop, `Stopping kea-ctrl-agent')
		check(`killall D_sbindir/kea-ctrl-agent')
	block_end

main_end
