# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/kea/kea-dhcp6.init
# Copyright (C) 2021 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---
#
# Desc: kea-dhcp6 daemon
# Runlevel: 98 rcX
#

main_begin

	block_begin(start, `Starting kea-dhcp6')
		D_sbindir/kea-dhcp6 -c /etc/kea/kea-dhcp6.conf &> /var/log/kea-dhcp6.log &
	block_end

	block_begin(stop, `Stopping kea-dhcp6')
		check(`killall D_sbindir/kea-dhcp6')
	block_end

main_end
