# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/lilo/etc-lilo.conf
# Copyright (C) 2004 - 2026 The T2 SDE Project
# Copyright (C) 1998 - 2003 ROCK Linux Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

boot=/dev/ide/host0/bus0/target0/lun0/disc
map=/boot/map
install=/boot/boot.b
prompt
timeout=100
lba32

default=linux

image=/boot/vmlinuz
	label = linux
	append = "root=/dev/ide/host0/bus0/target0/lun0/part1"
	read-only

image=/boot/vmlinuz.old
	label = linux.old
	append = "root=/dev/ide/host0/bus0/target0/lun0/part1"
	read-only
	optional

image=/boot/memtest86.bin
	label = memtest
	optional

# image=/boot/vmlinuz
#	label = raw
