#!/bin/sh
# 
# ROCK Linux: /etc/init.d/samba
#
# Desc: SMB (Server Message Block) protocol daemon
# Runlevel: 40 rcX
#

test -f /etc/opt/samba/smb.conf || exit 0

main_begin

    block_begin(start, `Starting SAMBA server.')
        check(`D_prefix/sbin/smbd -D')
        check(`D_prefix/sbin/nmbd -D')
    block_end

    block_begin(stop, `Stopping SAMBA server.')
       check(`killall -15 D_prefix/sbin/nmbd')
       check(`killall -15 D_prefix/sbin/smbd')
    block_end

main_end
