#!/bin/sh
# 
# ROCK Linux: /etc/init.d/smbmount
#
# Desc: mounting and unmountin for Windoze shares

test -f /etc/opt/samba/smb.conf || exit 0
  
case "$1" in
  start)
        echo "Mounting SMB shares: "
        mount -av -t smbfs
        ;;
  stop)   
        echo "Unmounting SMB shares: "
        umount -av -t smbfs
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage: $0 {start | stop | restart}"
        exit 1
        ;;
esac

exit 0
