# --- T2-COPYRIGHT-BEGIN ---
# t2/architecture/superh/pkg_btop_post.conf
# Copyright (C) 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

var_append CXX_WRAPPER_APPEND ' ' *btop_tools.cpp*?-O1
