# --- T2-COPYRIGHT-BEGIN ---
# t2/architecture/superh/pkg_glibc_post.conf
# Copyright (C) 2004 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---



# avoid undefined references to __fpscr_values which must be defined in
# crt1.o (so it is unavailable to libc objects)

[ $arch_machine = sh4 ] && hook_add premake 5 "cat > configparms <<-EOT
no-z-defs=yes
EOT
"
