# --- T2-COPYRIGHT-BEGIN ---
# t2/architecture/superh/pkg_linux_post.conf
# Copyright (C) 2004 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---
#lx_defconfig=arch/$lx_cpu/configs/"$SDECFG_SH_BOARDDEF"_defconfig

# generate a valid kernel config before running autoconf()
if [ "$SDECFG_SH_BOARDDEF" != "none" ]; then
	hook_add preconf 3 'eval $MAKE $makeopt ${SDECFG_SH_BOARDDEF}_defconfig'
fi
