# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/syslog-ng/syslog-ng.init
# Copyright (C) 2004 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---
#
# Desc: Next generation system logging utilities
# Runlevel: 11 rcX rc2 rc3 rc4 rc5
#

main_begin

    block_begin(start, `Starting system log ng daemon')
	check(`D_sbindir/syslog-ng')
    block_end

    block_begin(stop, `Stopping system log ng daemon')
	check(`killall D_sbindir/syslog-ng')
    block_end

main_end
