# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/docker-engine/dockerd.init
# Copyright (C) 2024 - 2025 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

# Desc: Docker daemon to manager containers
# Runlevel: 99
#

main_begin
	block_begin(start, `Starting docker engine')
		mount -t cgroup2 cgroup2 /sys/fs/cgroup
		D_bindir/dockerd &> /var/log/docker-engine.log &
	block_end

	block_begin(stop, `Stopping docker')
		check(`killall D_bindir/dockerd')
	block_end
main_end
