#!/bin/sh
#
# ROCK Linux: /etc/rc.d/init.d/spamd
#
# Desc: The spamassassin mail filter server
# Runlevel: 22 rcX
#

main_begin

    block_begin(start, `Starting spamd.')
        check(`D_prefix/bin/spamd -d')
    block_end

    block_begin(stop, `Stopping spamd.')
        check(`killall -15 spamd')
    block_end

    block_begin(restart, `Restarting exim.')
        check(`killall -1 spamd')
    block_end

main_end

