#!/bin/sh
# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/chromium-bsu/chromium-run
# Copyright (C) 2008 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

# (c) Rene Rebe <rene.rebe@gmx.net>
# to start chromium on dRock-Linux, now T2
#
export CHROMIUM_DATA=/usr/share/chromium/
export CHROMIUM_SCORE=/usr/share/chromium/scorefile
/usr/bin/chromium
