#!/bin/sh

version="@version@"
prefix="@prefix@"
libdir="@libdir@"
includedir="@includedir@"
pkglibdir="@pkglibdir@"
pkgdatadir="@pkgdatadir@"
LIBS="@LIBS@"
CFLAGS="@CFLAGS@"

usage()
{
  cat <<EOF
Usage: lua-config [OPTIONS]
Options:
 [--prefix]
 [--version]
 [--libs]
 [--cflags]
 [--pkglibdir]
 [--pkgdatadir]
EOF
  exit $1
}

if test $# -eq 0 ; then
  usage 1 1>&2
fi

while test $# -gt 0 ; do
  case $1 in
  --version) echo $version ;;
  --prefix) echo $prefix ;;
  --cflags) echo $CFLAGS ;;
  --libs) echo $LIBS ;;
  --pkglibdir) echo $pkglibdir ;;
  --pkgdatadir) echo $pkgdatadir ;;
  *)
    usage 1 1>&2
    ;;
  esac
  shift
done

