# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/scanlogd/scanlogd.init
# Copyright (C) 2004 - 2026 The T2 SDE Project
# Copyright (C) 1998 - 2004 ROCK Linux Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---
#
# Desc: Portscan-Monitor
# Runlevel: 90 rcX
#

main_begin

    block_begin(start, `Starting scanlog daemon')
	check(`D_sbindir/scanlogd')
    block_end
    block_begin(stop, `Stopping scanlog daemon')
	check(`killall D_sbindir/scanlogd')
    block_end

main_end
