# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/dovecot/dovecot.init
# Copyright (C) 2004 - 2025 The T2 SDE Project
# Copyright (C) 1998 - 2004 ROCK Linux Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---
#
# Desc: dovecot IMAP Daemon
# Runlevel: 60 rcX
#

main_begin

	block_begin(start, `Starting dovecot IMAP Daemon')
		check(`D_sbindir/dovecot')
	block_end

	block_begin(stop, `Stopping dovecot IMAP Daemon')
		check(`killall D_sbindir/dovecot')
	block_end

main_end
