# --- T2-COPYRIGHT-BEGIN ---
# t2/architecture/powerpc64/package/*/util-linux.conf
# Copyright (C) 2009 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---

# original code
[ -e $base/package/*/$pkg/$pkg.conf ] && . $base/package/*/$pkg/$pkg.conf

# we only need util-linux for e2fsprogs (which we need for yaboot)
# we do not also want to build a 32bit flavor of ncurses
if [ $arch_machine == powerpc ]; then
	var_append confopt ' ' '--without-python --without-ncurses --without-ncursesw'
	#var_append GCC_WRAPPRE_REMOVE ' ' '-lncursesw'

	hook_add preconf 5 "echo 'ac_cv_header_security_pam_appl_h=no
ac_cv_header_security_pam_misc_h=no' >> ./config.cache"
fi
