#!/bin/sh
#
# ROCK Linux: /etc/rc.d/init.d/nessusd
#
# Desc: Nessus daemon
#
# Runlevel: 25 rcX
#

main_begin

    block_begin(start, `Starting nessusd.')
	check(`D_prefix/sbin/nessusd -D')
    block_end

    block_begin(stop, `Stopping nessusd.')
	check(`killall -15 D_prefix/sbin/nessusd')
    block_end

    block_begin(restart, `Restarting nessusd.')
	check(`killall -1 D_prefix/sbin/nessusd')
    block_end

main_end
