# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/rpcbind/rpcbind.init
# Copyright (C) 2017 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---
#
# Desc: The RPC bind daemon
# Runlevel: 16 rcX
#

main_begin

    block_begin(start, `Starting rpcbind')
	check(`D_sbindir/rpcbind')
    block_end

    block_begin(stop, `Stopping rpcbind')
	check(`killall D_sbindir/rpcbind')
    block_end

main_end
