#!/bin/bash

if [ "$DNS1" -o "$DNS2" ] ; then
	sed -i -e '/^nameserver .* # automatically added$/d' /etc/resolv.conf
	(
	  echo "# added by /etc/ppp/ip-up during PPP connect ..."
	  [ "$DNS1" ] && echo "nameserver $DNS1 # automatically added"
	  [ "$DNS2" ] && echo "nameserver $DNS2 # automatically added"
	) >> /etc/resolv.conf
fi

