#!/bin/bash

if [ "$DNS1" -o "$DNS2" ] ; then
	sed -i '/^nameserver .*/d' /etc/resolv.conf
	(
	  echo "# added by /etc/ppp/ip-up during PPP connect ..."
	  [ "$DNS1" ] && echo "nameserver $DNS1"
	  [ "$DNS2" ] && echo "nameserver $DNS2"
	) >> /etc/resolv.conf
fi

