#!/bin/sh
# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/ppp/ip-up
# Copyright (C) 2022 - 2026 The T2 SDE Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---


if [ "$DNS1" -o "$DNS2" ]; then
	sed -i -e '/.*# automatically added/d' /etc/resolv.conf
	(
	  echo "# automatically added by $0 during PPP connect ..."
	  [ "$DNS1" ] && echo "nameserver $DNS1 # automatically added"
	  [ "$DNS2" ] && echo "nameserver $DNS2 # automatically added"
	) >> /etc/resolv.conf
fi
