# --- T2-COPYRIGHT-NOTE-BEGIN ---
# This copyright note is auto-generated by scripts/Create-CopyPatch.
# 
# T2 SDE: package/*/sysfiles/issue-std.sh
# Copyright (C) 2021 The T2 SDE Project
# 
# More information can be found in the files COPYING and README.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License. A copy of the
# GNU General Public License can be found in the file COPYING.
# --- T2-COPYRIGHT-NOTE-END ---

cat > etc/issue << EOT
___________       _________
__  /__|__ \\____________  /____
_  __/___/ /_  ___/  __  /_  _ \\
/ /_ _  __/_(__  )/ /_/ / /  __/
\\__/ /____//____/ \\__,_/  \\___/

\t \d  --  \U online  --  line [\l].

Welcome to \n ($sdetxt, Kernel \r).

EOT
