# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/clamav/clamd.init
# Copyright (C) 2004 - 2026 The T2 SDE Project
# Copyright (C) 1998 - 2003 ROCK Linux Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---
#
# Desc: ClamAV Daemon
# Runlevel: 61 rcX
#

main_begin

    block_begin(start, `Starting clamd')
	check(`D_sbindir/clamd')
    block_end

    block_begin(stop, `Stopping clamd')
	check(`killall D_sbindir/clamd')
    block_end

main_end
