# --- T2-COPYRIGHT-BEGIN ---
# t2/package/*/acpid/acpid.init
# Copyright (C) 2004 - 2026 The T2 SDE Project
# Copyright (C) 1998 - 2004 ROCK Linux Project
# SPDX-License-Identifier: GPL-2.0
# --- T2-COPYRIGHT-END ---
#
# Desc: ACPI event daemon
#
# Runlevel: 10 rcX
#

main_begin

    block_begin(start, `Starting acpid')
	check(`D_sbindir/acpid')
    block_end

    block_begin(stop, `Stopping acpid')
	check(`killall D_sbindir/acpid')
    block_end

main_end
