#!/bin/sh
#
# --- ROCK-COPYRIGHT-NOTE-BEGIN ---
# 
# This copyright note is auto-generated by ./scripts/Create-CopyPatch.
# Please add additional copyright information _after_ the line containing
# the ROCK-COPYRIGHT-NOTE-END tag. Otherwise it might get removed by
# the ./scripts/Create-CopyPatch script. Do not edit this copyright text!
# 
# ROCK Linux: rock-src/misc/tools-source/fl_wrapper_test.sh
# ROCK Linux is Copyright (C) 1998 - 2003 Clifford Wolf
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version. A copy of the GNU General Public
# License can be found at Documentation/COPYING.
# 
# Many people helped and are helping developing ROCK Linux. Please
# have a look at http://www.rocklinux.org/ and the Documentation/TEAM
# file for details.
# 
# --- ROCK-COPYRIGHT-NOTE-END ---

for x in exec{l,v}{,p,e} ; do
touch fltest_$x ; done

sh fl_wrapper.c.sh > fl_wrapper.c
gcc -Wall -O2 -ldl -shared -o fl_wrapper.so fl_wrapper.c

echo -n > rlog.txt
echo -n > wlog.txt

export FLWRAPPER_RLOG=rlog.txt
export FLWRAPPER_WLOG=wlog.txt

gcc fl_wrapper_test.c -o fltest_bin
LD_PRELOAD=./fl_wrapper.so ./fltest_bin

rm fltest_* fl_wrapper.so

